### ISSUE TITLE
How do we know which version of icons is used?

### ISSUE THREAD

**Issue by rogersam** [itsjavi/fontawesome-iconpicker#27]
Great plugin! thanks for making it! 

I am going to store the icons list in a database table, so I need to know which version of the font awesome icon library is used in this plugin?

How can I use the latest fa library?

thanks!

**Comment by itsjavi** [comment]
Font Awesome does not offer a way to list all icons, so the different icon names need to be inside the code of the plugin. Supported versions are usually specified in the releases page: https://github.com/itsjavi/fontawesome-iconpicker/releases
